/**
 * Firestore Service -- Contact Form, Admin Dashboard, Client Portal
 * 
 * Ye file handle karti hai:
 * 1. Contact form submissions save karna
 * 2. Admin dashboard ke liye data fetch karna
 * 3. Client portal ke liye project tracking
 * 4. Contact status update karna
 */

import {
  collection,
  addDoc,
  getDocs,
  doc,
  updateDoc,
  deleteDoc,
  query,
  orderBy,
  Timestamp,
  where,
} from 'firebase/firestore'
import { db, isFirebaseConfigured } from './config'
import { DATABASE } from '@/config/site-config'
import { getInstagramDMLink } from '@/lib/instagram'

// ==================== TYPES ====================

export type ContactStatus = 'new' | 'read' | 'replied'

export interface ContactSubmission {
  id?: string
  fullName: string
  businessName: string
  instagramHandle: string
  service: string
  message: string
  status: ContactStatus
  createdAt: Timestamp
  source: 'contact-form' | 'instagram'
}

export type ProjectStatus = 'inquiry' | 'discussion' | 'confirmed' | 'in-progress' | 'review' | 'delivered' | 'cancelled'

export interface ProjectInquiry {
  id?: string
  contactId: string
  clientName: string
  clientEmail: string
  businessName: string
  projectType: string
  budget: string
  deadline: string
  status: ProjectStatus
  progress: number
  deliveryDate: string
  adminNotes: string
  notes: string
  createdAt: Timestamp
  updatedAt: Timestamp
}

// ==================== HELPERS ====================

function getContactsCollection() {
  if (!db) throw new Error('Firestore not initialized')
  return collection(db, DATABASE.collections.contacts)
}

function getProjectsCollection() {
  if (!db) throw new Error('Firestore not initialized')
  return collection(db, DATABASE.collections.projects)
}

// ==================== CONTACT FORM OPERATIONS ====================

/**
 * Contact Form Submit:
 * - Firebase mein save karta hai
 * - Instagram DM link generate karta hai
 */
export async function submitContactForm(data: {
  fullName: string
  businessName: string
  instagramHandle: string
  service: string
  message: string
}): Promise<{ success: boolean; docId?: string; instagramDmUrl?: string; error?: string }> {
  if (!isFirebaseConfigured || !db) {
    // Firebase not configured, just return Instagram DM link
    const dmMessage = `Hi Haziq! I'm ${data.fullName} from ${data.businessName || 'my business'}. I'm interested in your ${data.service} plan. ${data.message}`
    const instagramDmUrl = getInstagramDMLink(dmMessage)
    return { success: true, instagramDmUrl }
  }

  try {
    const contactsCollection = getContactsCollection()
    const docRef = await addDoc(contactsCollection, {
      ...data,
      status: 'new' as ContactStatus,
      source: 'contact-form' as const,
      createdAt: Timestamp.now(),
    })

    // Instagram DM URL with pre-filled message
    const dmMessage = `Hi Haziq! I'm ${data.fullName} from ${data.businessName || 'my business'}. I'm interested in your ${data.service} plan. ${data.message}`
    const instagramDmUrl = getInstagramDMLink(dmMessage)

    return {
      success: true,
      docId: docRef.id,
      instagramDmUrl,
    }
  } catch (error) {
    console.error('Firebase submission error:', error)
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// ==================== FREE MOCKUP OPERATIONS ====================

/**
 * Submit a Free Mockup request keyed by client_id.
 * - client_id is generated by Haziq and shared via DM.
 * - Saves the request + the logged-in user's email so Haziq can match it.
 */
export async function submitClientMockup(data: {
  clientId: string
  clientEmail: string
  businessName: string
  instagramHandle: string
  message: string
}): Promise<{ success: boolean; docId?: string; instagramDmUrl?: string; error?: string }> {
  const dmMessage = `Hi Haziq! I am requesting my FREE website mockup. Client ID: ${data.clientId}. Business: ${data.businessName || 'N/A'}. ${data.message}`
  const instagramDmUrl = getInstagramDMLink(dmMessage)

  if (!isFirebaseConfigured || !db) {
    return { success: true, instagramDmUrl }
  }

  try {
    const mockupsCollection = collection(db, DATABASE.collections.clientMockups)
    const docRef = await addDoc(mockupsCollection, {
      clientId: data.clientId,
      clientEmail: data.clientEmail,
      businessName: data.businessName,
      instagramHandle: data.instagramHandle,
      message: data.message,
      status: 'new',
      source: 'free-mockup',
      createdAt: Timestamp.now(),
    })
    return { success: true, docId: docRef.id, instagramDmUrl }
  } catch (error) {
    console.error('Mockup submission error:', error)
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// ==================== ADMIN: FETCH OPERATIONS ====================

/**
 * Get All Contacts (Admin Dashboard)
 */
export async function getAllContacts(): Promise<ContactSubmission[]> {
  if (!isFirebaseConfigured || !db) return []
  try {
    const contactsCollection = getContactsCollection()
    const q = query(contactsCollection, orderBy('createdAt', 'desc'))
    const snapshot = await getDocs(q)
    return snapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data(),
    })) as ContactSubmission[]
  } catch (error) {
    console.error('Fetch contacts error:', error)
    return []
  }
}

/**
 * Get New Contacts Count (Admin Dashboard Badge)
 */
export async function getNewContactsCount(): Promise<number> {
  if (!isFirebaseConfigured || !db) return 0
  try {
    const contactsCollection = getContactsCollection()
    const q = query(contactsCollection, where('status', '==', 'new'))
    const snapshot = await getDocs(q)
    return snapshot.size
  } catch (error) {
    console.error('Fetch new contacts count error:', error)
    return 0
  }
}

/**
 * Get All Project Inquiries (Admin Dashboard)
 */
export async function getAllProjects(): Promise<ProjectInquiry[]> {
  if (!isFirebaseConfigured || !db) return []
  try {
    const projectsCollection = getProjectsCollection()
    const q = query(projectsCollection, orderBy('updatedAt', 'desc'))
    const snapshot = await getDocs(q)
    return snapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data(),
    })) as ProjectInquiry[]
  } catch (error) {
    console.error('Fetch projects error:', error)
    return []
  }
}

/**
 * Get Projects by Client Email (Client Portal)
 * NOTE: We do NOT use orderBy here because that requires a composite index.
 * Instead, we sort client-side after fetching.
 */
export async function getProjectsByClientEmail(email: string): Promise<ProjectInquiry[]> {
  if (!isFirebaseConfigured || !db) return []
  try {
    const projectsCollection = getProjectsCollection()
    const q = query(
      projectsCollection,
      where('clientEmail', '==', email)
    )
    const snapshot = await getDocs(q)
    const projects = snapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data(),
    })) as ProjectInquiry[]
    // Sort client-side by updatedAt descending
    return projects.sort((a, b) => {
      const aTime = (a.updatedAt as unknown as { seconds: number } | null)?.seconds || 0
      const bTime = (b.updatedAt as unknown as { seconds: number } | null)?.seconds || 0
      return bTime - aTime
    })
  } catch (error) {
    console.error('Fetch client projects error:', error)
    return []
  }
}

// ==================== ADMIN: UPDATE OPERATIONS ====================

/**
 * Update Contact Status
 */
export async function updateContactStatus(
  contactId: string,
  status: ContactStatus
): Promise<boolean> {
  if (!isFirebaseConfigured || !db) return false
  try {
    const docRef = doc(db, DATABASE.collections.contacts, contactId)
    await updateDoc(docRef, { status })
    return true
  } catch (error) {
    console.error('Update contact status error:', error)
    return false
  }
}

/**
 * Add Project Inquiry (Admin or Client)
 */
export async function addProjectInquiry(data: Omit<ProjectInquiry, 'id' | 'createdAt' | 'updatedAt'>): Promise<string | null> {
  if (!isFirebaseConfigured || !db) return null
  try {
    const projectsCollection = getProjectsCollection()
    const docRef = await addDoc(projectsCollection, {
      ...data,
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
    })
    return docRef.id
  } catch (error) {
    console.error('Add project inquiry error:', error)
    return null
  }
}

/**
 * Client submits a new project request
 */
export async function submitClientProject(data: {
  clientName: string
  clientEmail: string
  businessName: string
  projectType: string
  budget: string
  notes: string
}): Promise<string | null> {
  if (!isFirebaseConfigured || !db) return null
  try {
    const projectsCollection = getProjectsCollection()
    const docRef = await addDoc(projectsCollection, {
      contactId: '',
      clientName: data.clientName,
      clientEmail: data.clientEmail,
      businessName: data.businessName,
      projectType: data.projectType,
      budget: data.budget,
      deadline: '',
      status: 'inquiry' as ProjectStatus,
      progress: 0,
      deliveryDate: '',
      adminNotes: '',
      notes: data.notes,
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
    })
    return docRef.id
  } catch (error) {
    console.error('Submit client project error:', error)
    return null
  }
}

/**
 * Update Project Status
 */
export async function updateProjectStatus(
  projectId: string,
  status: ProjectStatus,
  notes?: string
): Promise<boolean> {
  if (!isFirebaseConfigured || !db) return false
  try {
    const docRef = doc(db, DATABASE.collections.projects, projectId)
    await updateDoc(docRef, {
      status,
      ...(notes ? { notes } : {}),
      updatedAt: Timestamp.now(),
    })
    return true
  } catch (error) {
    console.error('Update project status error:', error)
    return false
  }
}

/**
 * Update Project Details (Admin - progress, delivery, notes, etc.)
 */
export async function updateProjectDetails(
  projectId: string,
  updates: {
    status?: ProjectStatus
    progress?: number
    deliveryDate?: string
    adminNotes?: string
    budget?: string
    deadline?: string
    notes?: string
  }
): Promise<boolean> {
  if (!isFirebaseConfigured || !db) return false
  try {
    const docRef = doc(db, DATABASE.collections.projects, projectId)
    await updateDoc(docRef, {
      ...updates,
      updatedAt: Timestamp.now(),
    })
    return true
  } catch (error) {
    console.error('Update project details error:', error)
    return false
  }
}

/**
 * Delete Contact
 */
export async function deleteContact(contactId: string): Promise<boolean> {
  if (!isFirebaseConfigured || !db) return false
  try {
    const docRef = doc(db, DATABASE.collections.contacts, contactId)
    await deleteDoc(docRef)
    return true
  } catch (error) {
    console.error('Delete contact error:', error)
    return false
  }
}

/**
 * Delete Project
 */
export async function deleteProject(projectId: string): Promise<boolean> {
  if (!isFirebaseConfigured || !db) return false
  try {
    const docRef = doc(db, DATABASE.collections.projects, projectId)
    await deleteDoc(docRef)
    return true
  } catch (error) {
    console.error('Delete project error:', error)
    return false
  }
}

// ==================== UPLOADS (Image Gallery) ====================

export type UploadedImage = {
  id: string
  url: string
  thumb: string
  label: string
  category: string
  originalName: string
  createdAt: Date | null
}

export async function getUploadedImages(): Promise<UploadedImage[]> {
  if (!isFirebaseConfigured || !db) return []
  try {
    const q = query(collection(db, DATABASE.collections.uploads), orderBy('createdAt', 'desc'))
    const snapshot = await getDocs(q)
    return snapshot.docs.map(doc => {
      const data = doc.data()
      return {
        id: doc.id,
        url: data.url || '',
        thumb: data.thumb || data.url || '',
        label: data.label || '',
        category: data.category || 'general',
        originalName: data.originalName || '',
        createdAt: data.createdAt?.toDate?.() || null,
      }
    })
  } catch (error) {
    console.error('Get uploads error:', error)
    return []
  }
}

export async function deleteUpload(uploadId: string): Promise<boolean> {
  if (!isFirebaseConfigured || !db) return false
  try {
    await deleteDoc(doc(db, DATABASE.collections.uploads, uploadId))
    return true
  } catch (error) {
    console.error('Delete upload error:', error)
    return false
  }
}

// ==================== SSH KEYS ====================

export type SSHKey = {
  id: string
  name: string
  type: string
  host: string
  keyPreview: string
  createdAt: Date | null
}

export async function getSSHKeys(): Promise<SSHKey[]> {
  if (!isFirebaseConfigured || !db) return []
  try {
    const q = query(collection(db, DATABASE.collections.sshKeys), orderBy('createdAt', 'desc'))
    const snapshot = await getDocs(q)
    return snapshot.docs.map(doc => {
      const data = doc.data()
      // Use btoa/atob for browser compatibility (Buffer is Node.js only)
      let keyPreview = ''
      try {
        if (data.keyEncoded) {
          const decoded = atob(data.keyEncoded)
          keyPreview = decoded.substring(0, 40) + (decoded.length > 40 ? '...' : '')
        }
      } catch { keyPreview = '(encoded)' }
      return {
        id: doc.id,
        name: data.name || '',
        type: data.type || 'deploy',
        host: data.host || '',
        keyPreview,
        createdAt: data.createdAt?.toDate?.() || null,
      }
    })
  } catch (error) {
    console.error('Get SSH keys error:', error)
    return []
  }
}

export async function addSSHKey(name: string, type: string, host: string, privateKey: string): Promise<string | null> {
  if (!isFirebaseConfigured || !db) return null
  try {
    // Use btoa for browser compatibility (Buffer is Node.js only)
    const keyEncoded = btoa(privateKey)
    const docRef = await addDoc(collection(db, DATABASE.collections.sshKeys), {
      name,
      type,
      host,
      keyEncoded,
      createdAt: Timestamp.now(),
    })
    return docRef.id
  } catch (error) {
    console.error('Add SSH key error:', error)
    return null
  }
}

export async function deleteSSHKey(keyId: string): Promise<boolean> {
  if (!isFirebaseConfigured || !db) return false
  try {
    await deleteDoc(doc(db, DATABASE.collections.sshKeys, keyId))
    return true
  } catch (error) {
    console.error('Delete SSH key error:', error)
    return false
  }
}

// ==================== VIDEOS / REELS ====================

export type VideoPlatform = 'youtube' | 'instagram' | 'other'

export type VideoEntry = {
  id: string
  url: string              // Original URL user pasted
  platform: VideoPlatform  // Auto-detected: youtube/instagram/other
  embedUrl: string         // Embed-ready URL for iframe
  thumbnail: string        // YouTube auto-thumb, Instagram placeholder
  title: string            // User-given title
  description: string      // User-given description
  createdAt: Date | null
}

/**
 * Parse URL to detect platform and generate embed URL + thumbnail
 */
function parseVideoUrl(url: string): { platform: VideoPlatform; embedUrl: string; thumbnail: string } {
  // YouTube patterns
  const ytMatch = url.match(/(?:youtube\.com\/(?:watch\?v=|embed\/|shorts\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})/)
  if (ytMatch) {
    const videoId = ytMatch[1]
    return {
      platform: 'youtube',
      embedUrl: `https://www.youtube.com/embed/${videoId}`,
      thumbnail: `https://img.youtube.com/vi/${videoId}/mqdefault.jpg`,
    }
  }

  // Instagram patterns (reels, posts)
  const igMatch = url.match(/instagram\.com\/(?:reel|p|tv)\/([a-zA-Z0-9_-]+)/)
  if (igMatch) {
    const shortcode = igMatch[1]
    return {
      platform: 'instagram',
      embedUrl: `https://www.instagram.com/reel/${shortcode}/embed/`,
      thumbnail: '',  // Instagram thumbnails need oEmbed API, leave empty
    }
  }

  // Fallback
  return {
    platform: 'other',
    embedUrl: url,
    thumbnail: '',
  }
}

export async function getVideos(): Promise<VideoEntry[]> {
  if (!isFirebaseConfigured || !db) return []
  try {
    const q = query(collection(db, DATABASE.collections.videos), orderBy('createdAt', 'desc'))
    const snapshot = await getDocs(q)
    return snapshot.docs.map(doc => {
      const data = doc.data()
      return {
        id: doc.id,
        url: data.url || '',
        platform: data.platform || 'other',
        embedUrl: data.embedUrl || '',
        thumbnail: data.thumbnail || '',
        title: data.title || '',
        description: data.description || '',
        createdAt: data.createdAt?.toDate?.() || null,
      }
    })
  } catch (error) {
    console.error('Get videos error:', error)
    return []
  }
}

export async function addVideo(url: string, title: string, description: string): Promise<string | null> {
  if (!isFirebaseConfigured || !db) return null
  try {
    const parsed = parseVideoUrl(url)
    const docRef = await addDoc(collection(db, DATABASE.collections.videos), {
      url,
      platform: parsed.platform,
      embedUrl: parsed.embedUrl,
      thumbnail: parsed.thumbnail,
      title,
      description,
      createdAt: Timestamp.now(),
    })
    return docRef.id
  } catch (error) {
    console.error('Add video error:', error)
    return null
  }
}

export async function deleteVideo(videoId: string): Promise<boolean> {
  if (!isFirebaseConfigured || !db) return false
  try {
    await deleteDoc(doc(db, DATABASE.collections.videos, videoId))
    return true
  } catch (error) {
    console.error('Delete video error:', error)
    return false
  }
}

// ==================== CLIENT UPLOADS (Files/Images sent by clients) ====================
// Clients upload images -> only Admin can view + download (and client sees own)

export type ClientUpload = {
  id: string
  clientEmail: string
  clientName: string
  url: string
  thumb: string
  label: string
  fileName: string
  size: number
  type: string
  createdAt: Date | null
}

/** Client uploads an image/file (stored with their email) */
export async function addClientUpload(data: {
  clientEmail: string
  clientName: string
  url: string
  thumb: string
  label: string
  fileName: string
  size: number
  type: string
}): Promise<string | null> {
  if (!isFirebaseConfigured || !db) return null
  try {
    const docRef = await addDoc(collection(db, DATABASE.collections.clientUploads), {
      clientEmail: data.clientEmail,
      clientName: data.clientName,
      url: data.url,
      thumb: data.thumb || data.url,
      label: data.label,
      fileName: data.fileName,
      size: data.size,
      type: data.type,
      createdAt: Timestamp.now(),
    })
    return docRef.id
  } catch (error) {
    console.error('Add client upload error:', error)
    return null
  }
}

/** Admin: get ALL client uploads */
export async function getAllClientUploads(): Promise<ClientUpload[]> {
  if (!isFirebaseConfigured || !db) return []
  try {
    const q = query(collection(db, DATABASE.collections.clientUploads), orderBy('createdAt', 'desc'))
    const snapshot = await getDocs(q)
    return snapshot.docs.map(doc => {
      const data = doc.data()
      return {
        id: doc.id,
        clientEmail: data.clientEmail || '',
        clientName: data.clientName || '',
        url: data.url || '',
        thumb: data.thumb || data.url || '',
        label: data.label || '',
        fileName: data.fileName || '',
        size: data.size || 0,
        type: data.type || '',
        createdAt: data.createdAt?.toDate?.() || null,
      }
    })
  } catch (error) {
    console.error('Get client uploads error:', error)
    return []
  }
}

/** Client: get only their own uploads */
export async function getClientUploadsByEmail(email: string): Promise<ClientUpload[]> {
  if (!isFirebaseConfigured || !db) return []
  try {
    const q = query(
      collection(db, DATABASE.collections.clientUploads),
      where('clientEmail', '==', email)
    )
    const snapshot = await getDocs(q)
    const items = snapshot.docs.map(doc => {
      const data = doc.data()
      return {
        id: doc.id,
        clientEmail: data.clientEmail || '',
        clientName: data.clientName || '',
        url: data.url || '',
        thumb: data.thumb || data.url || '',
        label: data.label || '',
        fileName: data.fileName || '',
        size: data.size || 0,
        type: data.type || '',
        createdAt: data.createdAt?.toDate?.() || null,
      } as ClientUpload
    })
    // sort client-side by createdAt desc (no composite index needed)
    return items.sort((a, b) => {
      const at = a.createdAt?.getTime() || 0
      const bt = b.createdAt?.getTime() || 0
      return bt - at
    })
  } catch (error) {
    console.error('Get client uploads by email error:', error)
    return []
  }
}

/** Delete a client upload (admin or owner) */
export async function deleteClientUpload(id: string): Promise<boolean> {
  if (!isFirebaseConfigured || !db) return false
  try {
    await deleteDoc(doc(db, DATABASE.collections.clientUploads, id))
    return true
  } catch (error) {
    console.error('Delete client upload error:', error)
    return false
  }
}
